/*
 * generated by Xtext
 */
package org.blended.goal.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.outline.IOutlineTreeProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GoalUiModule extends org.blended.goal.ui.AbstractGoalUiModule {
	public GoalUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IOutlineTreeProvider> bindIOutlineTreeProvider() {
		return GoalOutlineTransformer.class;
	}
}
