/*
 * generated by Xtext
 */
package org.blended.condition.ui.contentassist

import org.blended.condition.ui.contentassist.AbstractConditionProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ConditionProposalProvider extends AbstractConditionProposalProvider {
}
