/**
 * generated by Xtext
 */
package org.blended.condition.validation;

import org.blended.condition.validation.AbstractConditionValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ConditionValidator extends AbstractConditionValidator {
}
