/*
 * generated by Xtext
 */
package org.blended.goal.validation

import org.blended.goal.goal.GoalModel
import org.blended.goal.goal.GoalPackage
import org.blended.goal.repository.GoalInterface
import org.eclipse.xtext.validation.Check
import org.eclipse.xtext.validation.CheckType

import static extension org.eclipse.xtext.EcoreUtil2.*

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class GoalValidator extends AbstractGoalValidator {

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(GoalModel model) {
//		println("HOLA")
////		if (!Character.isUpperCase(greeting.name.charAt(0))) {
////			warning('Name should start with a capital', 
////					MyDslPackage.Literals.GREETING__NAME,
////					INVALID_NAME)
////		}
//	def checkGreetingStartsWithCapital(Goal goal) {
//				println("Goal")
//	}

	@Check(CheckType.NORMAL)
	def checkModel(GoalModel model) {
				info('everything OK 0', GoalPackage.Literals.GOAL_MODEL__SPECIFICATION)
		var instance = GoalInterface.getInstance
				info('everything OK 2', GoalPackage.Literals.GOAL_MODEL__SPECIFICATION)
		var specId = model.eResource.normalizedURI.lastSegment.split("\\.").get(0)
				info('everything OK 3', GoalPackage.Literals.GOAL_MODEL__SPECIFICATION)
		var notification = instance.loadGoalModel(specId, model)
				info('everything OK 4', GoalPackage.Literals.GOAL_MODEL__SPECIFICATION)
		if (notification.hasErrors)
			for (error : notification.error)
				error(error.type.toString + "-" + error.value, GoalPackage.Literals.GOAL_MODEL__SPECIFICATION)
		else
			info('everything OK 2', GoalPackage.Literals.GOAL_MODEL__SPECIFICATION)
	}

}
