/*
 * generated by Xtext
 */
package org.blended.goal.validation

import org.eclipse.xtext.validation.Check
import org.blended.goal.goal.GoalModel

//import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class GoalValidator extends AbstractGoalValidator {

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(GoalModel model) {
//		println("HOLA")
////		if (!Character.isUpperCase(greeting.name.charAt(0))) {
////			warning('Name should start with a capital', 
////					MyDslPackage.Literals.GREETING__NAME,
////					INVALID_NAME)
////		}
//	}
}
