/**
 * generated by Xtext
 */
package org.blended.goal.ui.labeling;

import com.google.inject.Inject;
import org.blended.goal.goal.Goal;
import org.blended.goal.goal.GoalModel;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class GoalLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public GoalLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String image(final GoalModel cm) {
    return "goal.gif";
  }
  
  public String text(final GoalModel cm) {
    return "Goals";
  }
  
  public String image(final Goal g) {
    return "goal.png";
  }
}
