/*
 * generated by Xtext 2.12.0
 */
package pt.ist.socialsoftware.blendedworkflow.designer.idea.lang


class BlendedWorkflowFileType extends AbstractBlendedWorkflowFileType {
	public static final BlendedWorkflowFileType INSTANCE = new BlendedWorkflowFileType()
	
	new() {
		super(BlendedWorkflowLanguage.INSTANCE)
	}
}
