/*
 * generated by Xtext
 */
package org.blended.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.blended.services.BlendedGrammarAccess;

public class BlendedParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BlendedGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.blended.parser.antlr.internal.InternalBlendedParser createParser(XtextTokenStream stream) {
		return new org.blended.parser.antlr.internal.InternalBlendedParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "BlendedModel";
	}
	
	public BlendedGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BlendedGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
