/**
 * generated by Xtext
 */
package org.blended.goal.validation;

import org.blended.goal.validation.AbstractGoalValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GoalValidator extends AbstractGoalValidator {
}
