/**
 * generated by Xtext
 */
package org.blended.ui.contentassist;

import org.blended.ui.contentassist.AbstractBlendedProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class BlendedProposalProvider extends AbstractBlendedProposalProvider {
}
