/*
 * generated by Xtext
 */
package org.blended.common.ui.contentassist

import org.blended.common.ui.contentassist.AbstractCommonProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class CommonProposalProvider extends AbstractCommonProposalProvider {
}
