/*
 * generated by Xtext
 */
package org.blended.activity;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ActivityRuntimeModule extends org.blended.activity.AbstractActivityRuntimeModule {

}
