//grammar org.blended.activity.Activity with org.eclipse.xtext.common.Terminals
grammar org.blended.activity.Activity with org.blended.common.Common

generate activity "http://www.blended.org/activity/Activity"

ActivityModel:
	specification = Specification
	activities += Activity+
;

Activity:
	name = ID ':' description = STRING
	'PRE' '(' (pre += (EntityAchieveCondition | MandatoryAttributeAchieveCondition | NotMandatoryAttributeAchieveCondition) (',' pre += (EntityAchieveCondition | MandatoryAttributeAchieveCondition | NotMandatoryAttributeAchieveCondition))*)? ')'','
	'POST' '(' (post += (EntityAchieveCondition | MandatoryAttributeAchieveCondition | NotMandatoryAttributeAchieveCondition | EntityInvariantCondition | AttributeInvariantCondition) 
	(',' post += (EntityAchieveCondition | MandatoryAttributeAchieveCondition | NotMandatoryAttributeAchieveCondition | EntityInvariantCondition | AttributeInvariantCondition))*)?  ')'
;