/*
 * generated by Xtext
 */
package org.blended;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BlendedRuntimeModule extends org.blended.AbstractBlendedRuntimeModule {

}
