/*
 * generated by Xtext
 */
package org.blended;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BlendedStandaloneSetup extends BlendedStandaloneSetupGenerated{

	public static void doSetup() {
		new BlendedStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

