/*
 * generated by Xtext 2.12.0
 */
package pt.ist.socialsoftware.blendedworkflow.designer.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import pt.ist.socialsoftware.blendedworkflow.designer.idea.lang.BlendedWorkflowLanguage

class BlendedWorkflowCompletionContributor extends AbstractBlendedWorkflowCompletionContributor {
	new() {
		this(BlendedWorkflowLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
