/*
 * generated by Xtext 2.12.0
 */
package pt.ist.socialsoftware.blendedworkflow.designer.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class BlendedWorkflowWebModule extends AbstractBlendedWorkflowWebModule {
}
