/*
 * generated by Xtext
 */
package org.blended.common;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CommonRuntimeModule extends org.blended.common.AbstractCommonRuntimeModule {

}
