/*
 * generated by Xtext
 */
package org.blended.data;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DataUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.blended.data.ui.internal.DataActivator.getInstance().getInjector("org.blended.data.Data");
	}
	
}
