/*
 * generated by Xtext
 */
package org.blended.condition.serializer;

import com.google.inject.Inject;
import com.google.inject.Provider;
import org.blended.blended.Activity;
import org.blended.blended.And;
import org.blended.blended.AttributeDefinition;
import org.blended.blended.AttributeDependenceCondition;
import org.blended.blended.AttributeInvariantCondition;
import org.blended.blended.AttributeValue;
import org.blended.blended.BlendedPackage;
import org.blended.blended.Condition;
import org.blended.blended.EntityAchieveCondition;
import org.blended.blended.EntityAchieveConditionExist;
import org.blended.blended.EntityDependenceCondition;
import org.blended.blended.EntityInvariantCondition;
import org.blended.blended.Goal;
import org.blended.blended.MandatoryAttributeAchieveCondition;
import org.blended.blended.Not;
import org.blended.blended.NotMandatoryAttributeAchieveCondition;
import org.blended.blended.Nothing;
import org.blended.blended.Or;
import org.blended.condition.condition.ConditionModel;
import org.blended.condition.condition.ConditionPackage;
import org.blended.condition.services.ConditionGrammarAccess;
import org.blended.serializer.BlendedSemanticSequencer;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.serializer.acceptor.ISemanticSequenceAcceptor;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.diagnostic.ISemanticSequencerDiagnosticProvider;
import org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic.Acceptor;
import org.eclipse.xtext.serializer.sequencer.GenericSequencer;
import org.eclipse.xtext.serializer.sequencer.ISemanticNodeProvider.INodesForEObjectProvider;
import org.eclipse.xtext.serializer.sequencer.ISemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class ConditionSemanticSequencer extends BlendedSemanticSequencer {

	@Inject
	private ConditionGrammarAccess grammarAccess;
	
	@Override
	public void createSequence(EObject context, EObject semanticObject) {
		if(semanticObject.eClass().getEPackage() == BlendedPackage.eINSTANCE) switch(semanticObject.eClass().getClassifierID()) {
			case BlendedPackage.ACTIVITY:
				sequence_Activity(context, (Activity) semanticObject); 
				return; 
			case BlendedPackage.AND:
				sequence_And(context, (And) semanticObject); 
				return; 
			case BlendedPackage.ATTRIBUTE_DEFINITION:
				sequence_Atomic(context, (AttributeDefinition) semanticObject); 
				return; 
			case BlendedPackage.ATTRIBUTE_DEPENDENCE_CONDITION:
				sequence_AttributeDependenceCondition(context, (AttributeDependenceCondition) semanticObject); 
				return; 
			case BlendedPackage.ATTRIBUTE_INVARIANT_CONDITION:
				sequence_AttributeInvariantCondition(context, (AttributeInvariantCondition) semanticObject); 
				return; 
			case BlendedPackage.ATTRIBUTE_VALUE:
				sequence_Atomic(context, (AttributeValue) semanticObject); 
				return; 
			case BlendedPackage.CONDITION:
				sequence_Condition(context, (Condition) semanticObject); 
				return; 
			case BlendedPackage.ENTITY_ACHIEVE_CONDITION:
				sequence_EntityAchieveCondition(context, (EntityAchieveCondition) semanticObject); 
				return; 
			case BlendedPackage.ENTITY_ACHIEVE_CONDITION_EXIST:
				sequence_EntityAchieveConditionExist(context, (EntityAchieveConditionExist) semanticObject); 
				return; 
			case BlendedPackage.ENTITY_DEPENDENCE_CONDITION:
				sequence_EntityDependenceCondition(context, (EntityDependenceCondition) semanticObject); 
				return; 
			case BlendedPackage.ENTITY_INVARIANT_CONDITION:
				sequence_EntityInvariantCondition(context, (EntityInvariantCondition) semanticObject); 
				return; 
			case BlendedPackage.GOAL:
				sequence_Goal(context, (Goal) semanticObject); 
				return; 
			case BlendedPackage.MANDATORY_ATTRIBUTE_ACHIEVE_CONDITION:
				sequence_MandatoryAttributeAchieveCondition(context, (MandatoryAttributeAchieveCondition) semanticObject); 
				return; 
			case BlendedPackage.NOT:
				sequence_Primary(context, (Not) semanticObject); 
				return; 
			case BlendedPackage.NOT_MANDATORY_ATTRIBUTE_ACHIEVE_CONDITION:
				sequence_NotMandatoryAttributeAchieveCondition(context, (NotMandatoryAttributeAchieveCondition) semanticObject); 
				return; 
			case BlendedPackage.NOTHING:
				sequence_Nothing(context, (Nothing) semanticObject); 
				return; 
			case BlendedPackage.OR:
				sequence_Or(context, (Or) semanticObject); 
				return; 
			}
		else if(semanticObject.eClass().getEPackage() == ConditionPackage.eINSTANCE) switch(semanticObject.eClass().getClassifierID()) {
			case ConditionPackage.CONDITION_MODEL:
				sequence_ConditionModel(context, (ConditionModel) semanticObject); 
				return; 
			}
		if (errorAcceptor != null) errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Constraint:
	 *     conditions=Condition
	 */
	protected void sequence_ConditionModel(EObject context, ConditionModel semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, ConditionPackage.Literals.CONDITION_MODEL__CONDITIONS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ConditionPackage.Literals.CONDITION_MODEL__CONDITIONS));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getConditionModelAccess().getConditionsConditionParserRuleCall_0(), semanticObject.getConditions());
		feeder.finish();
	}
}
