package pt.ist.socialsoftware.blendedworkflow.presentation;

public class BWCase {

//	// given by user
//	private String caseName;
//	// generated by worklist handler
//	private String caseInstanceID;
//	
//	// data model URI
//	private String dataModelURI;
//	
//	// yawl spec uri
//	private String yawlSpecName;
//	// yawl spec version
//	private String yawlSpecVersion;
//	// yawl spec
//	private String yawlSpec;
//	// yawl spec uuid
//	private String yawlSpecID;
//	// yawl instance ID
//	private String yawlInstanceID;
//	
//	// bw spec uri
//	private String bwSpecName;
//	// bw spec
//	private String bwSpec;
//	// bw spec uuid
//	private String bwSpecId;
//
//	// goal spec uri
//	private String goalSpecId;
//	// conditions spec uri
//	private String condsSpecId;
//	// goal instance ID
//	private String goalInstanceID;
//	
//	// Tasks (=activities). item=taskID
//	private ArrayList<String> activeTasks = new ArrayList<String>();
//	private ArrayList<String> executedTasks = new ArrayList<String>();
//	private ArrayList<String> skippedTasks = new ArrayList<String>();
//	
//	//Goals. item=goalID
//	private ArrayList<String> activeGoals = new ArrayList<String>();
//	private ArrayList<String> executedGoals = new ArrayList<String>();
//	private ArrayList<String> skippedGoals = new ArrayList<String>();
//	private ArrayList<String> newGoals = new ArrayList<String>();
//	
//	
//	public BWCase(String name) {
//		this.caseName = name;
//	}
//
//	/*********** GETTERS *************/
//	public String getCaseName() { return caseName; }
//	public String getCaseID() {	return caseInstanceID; }
//	public String getDataModelURI() { return this.dataModelURI; }
//	public String getYAWLspec() { return yawlSpec; }
//	public String getBWspec() { return bwSpec; }
//	public String getBWSpecName() {	return this.bwSpecName;	}
//	public String getYAWLSpecName() { return this.yawlSpecName; }
//	public String getYAWLSpecID() { return this.yawlSpecID;	}
//	public String getBWSpecID() { return this.bwSpecId; }
//	public String getYAWLSpecVersion() { return this.yawlSpecVersion; }
//	public String getGoalSpecID() { return this.goalSpecId; }
//	public String getConditionsSpecID() { return this.condsSpecId; }
//	public String getYAWLInstanceID() { return this.yawlInstanceID; }
//	public String getGoalInstanceID() { return this.goalInstanceID; }
//	public ArrayList<String> getActiveTasks() {	return activeTasks; }
//	public ArrayList<String> getExecutedTasks() { return executedTasks; }
//	public ArrayList<String> getSkippedTasks() { return skippedTasks; }
//	public ArrayList<String> getActiveGoals() {	return activeGoals;	}
//	public ArrayList<String> getExecutedGoals() { return executedGoals; }
//	public ArrayList<String> getSkippedGoals() { return skippedGoals; }
//	public ArrayList<String> getNewGoals() { return newGoals; }
//	/*********************************/
//
//	/************* SETTERS ***********/
//	public void setCaseName(String caseName) { this.caseName = caseName; }
//	public void setCaseID(String caseID) { this.caseInstanceID = caseID; }
//	public void setDataModelURI(String uri) { this.dataModelURI = uri; }
//	public void setYAWLspec(String yAWLspec) { this.yawlSpec = yAWLspec; }
//	public void setBWspec(String bWspec) { this.bwSpec = bWspec; }
//	public void setBWSpecName(String bwSpecName) { this.bwSpecName = bwSpecName; }
//	public void setYAWLSpecName(String yawlSpecName) { this.yawlSpecName = yawlSpecName; }
//	public void setYAWLSpecID(String id) { this.yawlSpecID = id; }
//	public void setBWSpecID(String id) { this.bwSpecId = id; }
//	public void setYAWLSpecVersion(String version) { this.yawlSpecVersion = version; }
//	public void setGoalSpecID(String id) { this.goalSpecId = id; }
//	public void setConditionsSpecID(String id) { this.condsSpecId = id; }
//	public void setYAWLInstanceID(String id) { this.yawlInstanceID = id; }
//	public void setGoalInstanceID(String id) { this.goalInstanceID = id; }
//	public void setActiveTasks(ArrayList<String> activeTasks) {	this.activeTasks = activeTasks; }
//	public void setExecutedTasks(ArrayList<String> executedTasks) {	this.executedTasks = executedTasks; }
//	public void setSkippedTasks(ArrayList<String> skippedTasks) { this.skippedTasks = skippedTasks; }
//	public void setActiveGoals(ArrayList<String> activeGoals) { this.activeGoals = activeGoals; }
//	public void setExecutedGoals(ArrayList<String> executedGoals) {	this.executedGoals = executedGoals; }
//	public void setSkippedGoals(ArrayList<String> skippedGoals) { this.skippedGoals = skippedGoals; }
//	public void setNewGoals(ArrayList<String> newGoals) { this.newGoals = newGoals; }
//	/*********************************/
//	
//	public String getTaskIDToDisplayFromTaskURI(String taskURI) {
//		String[] stringSplit = taskURI.split("\\:");
//		String activeTaskURI;
//		
//		if(stringSplit[0].contains(".")) {
//			String[] caseInstanceSplit = stringSplit[0].split("\\.");
//			activeTaskURI = caseInstanceSplit[0] + ":" + stringSplit[1];
//		} else {
//			activeTaskURI = taskURI;
//		}
//		
//		String task = null;
//		for (String activeTask : this.activeTasks) {
//			if(activeTask.equals(activeTaskURI)) {
//				task = activeTask;
//				break;
//			}
//		}
//		if(task == null) { return null; }
//		String[] taskSplitted = task.split("\\:");
//		return caseInstanceID + ":" + taskSplitted[1];
//	}
//	
//	public String getTaskURIFromTaskIDForDisplay(String taskIDForDisplay) {
//		String[] taskSplitted = taskIDForDisplay.split("\\:");
//		return this.yawlInstanceID + ":" + taskSplitted[1];
//	}
//	
//	public String getGoalURIFromGoalIDForDisplay(String goalIDForDisplay) {
//		String[] goalSplitted = goalIDForDisplay.split("\\:");
//		return this.goalInstanceID + ":" + goalSplitted[1];
//	}
//	
//	public void registerActiveTask(String taskURI) {
//		this.activeTasks.add(taskURI);
//	}
//	
//	public String getGoalIDToDisplayFromGoalURI(String goalURI) {
//		String goal = null;
//		for (String activeGoal : this.activeGoals) {
//			if(activeGoal.equals(goalURI)) {
//				goal = activeGoal;
//				break;
//			}
//		}
//		if(goal == null) { return null; }
//		String[] goalSplitted = goal.split("\\:");
//		return caseInstanceID + ":" + goalSplitted[1];
//	}
//	
//	public void registerExecutedTask(String taskIDForDisplay) {
//		String taskURI = getTaskURIFromTaskIDForDisplay(taskIDForDisplay);
//		this.activeTasks.remove(taskURI);
//		this.executedTasks.add(taskURI);
//	}
//	
//	public void registerExecutedGoal(String goalIDForDisplay) {
//		String goalURI = getGoalURIFromGoalIDForDisplay(goalIDForDisplay);
//		this.activeGoals.remove(goalURI);
//		this.executedGoals.add(goalURI);
//	}
//	
//	public boolean isTaskActive(String taskIDForDisplay) {
//		String taskURI = getTaskURIFromTaskIDForDisplay(taskIDForDisplay);
//		return this.activeTasks.contains(taskURI);
//	}
//	
//	public void registerSkippedTask(String taskIDForDisplay) {
//		String taskURI = getTaskURIFromTaskIDForDisplay(taskIDForDisplay);
//		this.activeTasks.remove(taskURI);
//		this.skippedTasks.add(taskURI);
//	}
//	public void registerActiveGoal(String goalURI) {
//		this.activeGoals.add(goalURI);
//	}
//	public void registerSkippedGoal(String goalIDForDisplay) {
//		String goalURI = getGoalURIFromGoalIDForDisplay(goalIDForDisplay);
//		this.activeGoals.remove(goalURI);
//		this.skippedGoals.add(goalURI);
//	}
//	public void registerNewGoal(String goalURI) {
//		this.newGoals.add(goalURI);
//	}
}
