/*
 * generated by Xtext
 */
package org.blended.condition.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.blended.condition.services.ConditionGrammarAccess;

public class ConditionParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ConditionGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.blended.condition.parser.antlr.internal.InternalConditionParser createParser(XtextTokenStream stream) {
		return new org.blended.condition.parser.antlr.internal.InternalConditionParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ConditionModel";
	}
	
	public ConditionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ConditionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
