/*
 * generated by Xtext
 */
package org.blended.activity.ui;

import org.blended.activity.ui.ActivityOutlineTransformer;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.outline.IOutlineTreeProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ActivityUiModule extends org.blended.activity.ui.AbstractActivityUiModule {
	public ActivityUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IOutlineTreeProvider> bindIOutlineTreeProvider() {
		return ActivityOutlineTransformer.class;
	}
}
