/*
 * generated by Xtext
 */
package org.blended.goal.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.blended.goal.ui.internal.GoalActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GoalExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GoalActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GoalActivator.getInstance().getInjector(GoalActivator.ORG_BLENDED_GOAL_GOAL);
	}
	
}
