/**
 * generated by Xtext
 */
package org.blended.validation;

import org.blended.validation.AbstractBlendedValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BlendedValidator extends AbstractBlendedValidator {
}
