/*
 * generated by Xtext
 */
package org.blended;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BlendedUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.blended.ui.internal.BlendedActivator.getInstance().getInjector("org.blended.Blended");
	}
	
}
