/**
 * generated by Xtext
 */
package org.blended.goal.ui.contentassist;

import org.blended.goal.ui.contentassist.AbstractGoalProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class GoalProposalProvider extends AbstractGoalProposalProvider {
}
