/*
 * generated by Xtext
 */
package org.blended.activity.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.blended.activity.services.ActivityGrammarAccess;

public class ActivityParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ActivityGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.blended.activity.parser.antlr.internal.InternalActivityParser createParser(XtextTokenStream stream) {
		return new org.blended.activity.parser.antlr.internal.InternalActivityParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ActivityModel";
	}
	
	public ActivityGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ActivityGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
