/**
 * generated by Xtext
 */
package org.blended.data.validation;

import org.blended.data.validation.AbstractDataValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DataValidator extends AbstractDataValidator {
}
