/**
 * generated by Xtext
 */
package org.blended.data.ui.contentassist;

import org.blended.data.ui.contentassist.AbstractDataProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DataProposalProvider extends AbstractDataProposalProvider {
}
