/*
 * generated by Xtext
 */
package org.blended.goal.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractGoalValidator extends org.blended.validation.BlendedValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
	    result.add(org.blended.goal.goal.GoalPackage.eINSTANCE);
		return result;
	}
}
