/*
 * generated by Xtext
 */
package org.blended.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.blended.ui.internal.BlendedActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BlendedExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BlendedActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BlendedActivator.getInstance().getInjector(BlendedActivator.ORG_BLENDED_BLENDED);
	}
	
}
