/*
 * generated by Xtext
 */
package org.blended.condition.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractConditionValidator extends org.blended.validation.BlendedValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
	    result.add(org.blended.condition.condition.ConditionPackage.eINSTANCE);
		return result;
	}
}
