/*
 * generated by Xtext
 */
package org.blended.condition;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ConditionUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.blended.condition.ui.internal.ConditionActivator.getInstance().getInjector("org.blended.condition.Condition");
	}
	
}
