/*
 * generated by Xtext 2.12.0
 */
package pt.ist.socialsoftware.blendedworkflow.designer


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BlendedWorkflowRuntimeModule extends AbstractBlendedWorkflowRuntimeModule {
}
