/*
 * generated by Xtext 2.12.0
 */
package pt.ist.socialsoftware.blendedworkflow.designer


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BlendedWorkflowStandaloneSetup extends BlendedWorkflowStandaloneSetupGenerated {

	def static void doSetup() {
		new BlendedWorkflowStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
