/*
 * generated by Xtext
 */
package org.blended.condition.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.blended.condition.ui.internal.ConditionActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ConditionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ConditionActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ConditionActivator.getInstance().getInjector(ConditionActivator.ORG_BLENDED_CONDITION_CONDITION);
	}
	
}
