/*
 * generated by Xtext
 */
package org.blended.condition.ui;

import org.blended.generator.CustomOutputConfigurationProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.generator.IOutputConfigurationProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConditionUiModule extends org.blended.condition.ui.AbstractConditionUiModule {
	public ConditionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IOutputConfigurationProvider> bindIOutputConfigurationProvider() {
		return CustomOutputConfigurationProvider.class;
	}
	
}
