/**
 * generated by Xtext
 */
package org.blended.data.ui.labeling;

import com.google.inject.Inject;
import org.blended.data.data.And;
import org.blended.data.data.Association;
import org.blended.data.data.Constraint;
import org.blended.data.data.DataModel;
import org.blended.data.data.Entity;
import org.blended.data.data.Not;
import org.blended.data.data.Or;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class DataLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public DataLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String image(final DataModel dm) {
    return "data.png";
  }
  
  public String image(final Entity e) {
    return "entity.gif";
  }
  
  public String image(final Association a) {
    return "association.png";
  }
  
  public String image(final Constraint c) {
    return "constraint.jpg";
  }
  
  public String text(final And and) {
    return "AND";
  }
  
  public String text(final Or or) {
    return "OR";
  }
  
  public String text(final Not not) {
    return "NOT";
  }
}
