/*
 * generated by Xtext
 */
package org.blended.condition.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.blended.condition.services.ConditionGrammarAccess;

public class ConditionParser extends AbstractContentAssistParser {
	
	@Inject
	private ConditionGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.blended.condition.ui.contentassist.antlr.internal.InternalConditionParser createParser() {
		org.blended.condition.ui.contentassist.antlr.internal.InternalConditionParser result = new org.blended.condition.ui.contentassist.antlr.internal.InternalConditionParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAttributeAchieveConditionAccess().getAlternatives(), "rule__AttributeAchieveCondition__Alternatives");
					put(grammarAccess.getCardinalityAccess().getAlternatives(), "rule__Cardinality__Alternatives");
					put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
					put(grammarAccess.getAtomicAccess().getAlternatives(), "rule__Atomic__Alternatives");
					put(grammarAccess.getConditionAccess().getEntityAchieveConditionsAlternatives_1_1_0(), "rule__Condition__EntityAchieveConditionsAlternatives_1_1_0");
					put(grammarAccess.getEntityAchieveConditionAccess().getGroup(), "rule__EntityAchieveCondition__Group__0");
					put(grammarAccess.getEntityAchieveConditionExistAccess().getGroup(), "rule__EntityAchieveConditionExist__Group__0");
					put(grammarAccess.getEntityInvariantConditionAccess().getGroup(), "rule__EntityInvariantCondition__Group__0");
					put(grammarAccess.getEntityDependenceConditionAccess().getGroup(), "rule__EntityDependenceCondition__Group__0");
					put(grammarAccess.getNotMandatoryAttributeAchieveConditionAccess().getGroup(), "rule__NotMandatoryAttributeAchieveCondition__Group__0");
					put(grammarAccess.getNotMandatoryAttributeAchieveConditionAccess().getGroup_3(), "rule__NotMandatoryAttributeAchieveCondition__Group_3__0");
					put(grammarAccess.getMandatoryAttributeAchieveConditionAccess().getGroup(), "rule__MandatoryAttributeAchieveCondition__Group__0");
					put(grammarAccess.getMandatoryAttributeAchieveConditionAccess().getGroup_5(), "rule__MandatoryAttributeAchieveCondition__Group_5__0");
					put(grammarAccess.getAttributeInvariantConditionAccess().getGroup(), "rule__AttributeInvariantCondition__Group__0");
					put(grammarAccess.getAttributeDependenceConditionAccess().getGroup(), "rule__AttributeDependenceCondition__Group__0");
					put(grammarAccess.getAttributeDependenceConditionAccess().getGroup_5(), "rule__AttributeDependenceCondition__Group_5__0");
					put(grammarAccess.getCardinalityAccess().getGroup_1(), "rule__Cardinality__Group_1__0");
					put(grammarAccess.getCardinalityAccess().getGroup_2(), "rule__Cardinality__Group_2__0");
					put(grammarAccess.getCardinalityAccess().getGroup_3(), "rule__Cardinality__Group_3__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup_3(), "rule__Attribute__Group_3__0");
					put(grammarAccess.getOrAccess().getGroup(), "rule__Or__Group__0");
					put(grammarAccess.getOrAccess().getGroup_1(), "rule__Or__Group_1__0");
					put(grammarAccess.getAndAccess().getGroup(), "rule__And__Group__0");
					put(grammarAccess.getAndAccess().getGroup_1(), "rule__And__Group_1__0");
					put(grammarAccess.getPrimaryAccess().getGroup_0(), "rule__Primary__Group_0__0");
					put(grammarAccess.getPrimaryAccess().getGroup_1(), "rule__Primary__Group_1__0");
					put(grammarAccess.getAtomicAccess().getGroup_0(), "rule__Atomic__Group_0__0");
					put(grammarAccess.getAtomicAccess().getGroup_1(), "rule__Atomic__Group_1__0");
					put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
					put(grammarAccess.getConditionAccess().getGroup_1(), "rule__Condition__Group_1__0");
					put(grammarAccess.getConditionAccess().getGroup_2(), "rule__Condition__Group_2__0");
					put(grammarAccess.getConditionAccess().getGroup_3(), "rule__Condition__Group_3__0");
					put(grammarAccess.getConditionAccess().getGroup_4(), "rule__Condition__Group_4__0");
					put(grammarAccess.getConditionAccess().getGroup_5(), "rule__Condition__Group_5__0");
					put(grammarAccess.getConditionAccess().getGroup_6(), "rule__Condition__Group_6__0");
					put(grammarAccess.getConditionModelAccess().getConditionsAssignment(), "rule__ConditionModel__ConditionsAssignment");
					put(grammarAccess.getEntityAchieveConditionAccess().getNameAssignment_2(), "rule__EntityAchieveCondition__NameAssignment_2");
					put(grammarAccess.getEntityAchieveConditionExistAccess().getNameAssignment_4(), "rule__EntityAchieveConditionExist__NameAssignment_4");
					put(grammarAccess.getEntityInvariantConditionAccess().getNameAssignment_2(), "rule__EntityInvariantCondition__NameAssignment_2");
					put(grammarAccess.getEntityInvariantConditionAccess().getCardinalityAssignment_4(), "rule__EntityInvariantCondition__CardinalityAssignment_4");
					put(grammarAccess.getEntityDependenceConditionAccess().getEntity1Assignment_4(), "rule__EntityDependenceCondition__Entity1Assignment_4");
					put(grammarAccess.getEntityDependenceConditionAccess().getEntity2Assignment_9(), "rule__EntityDependenceCondition__Entity2Assignment_9");
					put(grammarAccess.getNotMandatoryAttributeAchieveConditionAccess().getConditionsAssignment_2(), "rule__NotMandatoryAttributeAchieveCondition__ConditionsAssignment_2");
					put(grammarAccess.getNotMandatoryAttributeAchieveConditionAccess().getConditionsAssignment_3_1(), "rule__NotMandatoryAttributeAchieveCondition__ConditionsAssignment_3_1");
					put(grammarAccess.getMandatoryAttributeAchieveConditionAccess().getConditionsAssignment_4(), "rule__MandatoryAttributeAchieveCondition__ConditionsAssignment_4");
					put(grammarAccess.getMandatoryAttributeAchieveConditionAccess().getConditionsAssignment_5_1(), "rule__MandatoryAttributeAchieveCondition__ConditionsAssignment_5_1");
					put(grammarAccess.getAttributeInvariantConditionAccess().getExpressionAssignment_2(), "rule__AttributeInvariantCondition__ExpressionAssignment_2");
					put(grammarAccess.getAttributeDependenceConditionAccess().getAttributes1Assignment_4(), "rule__AttributeDependenceCondition__Attributes1Assignment_4");
					put(grammarAccess.getAttributeDependenceConditionAccess().getAttributes1Assignment_5_1(), "rule__AttributeDependenceCondition__Attributes1Assignment_5_1");
					put(grammarAccess.getAttributeDependenceConditionAccess().getAttribute2Assignment_10(), "rule__AttributeDependenceCondition__Attribute2Assignment_10");
					put(grammarAccess.getNothingAccess().getNameAssignment(), "rule__Nothing__NameAssignment");
					put(grammarAccess.getOrAccess().getRightAssignment_1_2(), "rule__Or__RightAssignment_1_2");
					put(grammarAccess.getAndAccess().getRightAssignment_1_2(), "rule__And__RightAssignment_1_2");
					put(grammarAccess.getPrimaryAccess().getExpressionAssignment_1_2(), "rule__Primary__ExpressionAssignment_1_2");
					put(grammarAccess.getAtomicAccess().getNameAssignment_0_3(), "rule__Atomic__NameAssignment_0_3");
					put(grammarAccess.getAtomicAccess().getNameAssignment_1_1(), "rule__Atomic__NameAssignment_1_1");
					put(grammarAccess.getConditionAccess().getEntityAchieveConditionsAssignment_1_1(), "rule__Condition__EntityAchieveConditionsAssignment_1_1");
					put(grammarAccess.getConditionAccess().getEntityInvariantConditionsAssignment_2_1(), "rule__Condition__EntityInvariantConditionsAssignment_2_1");
					put(grammarAccess.getConditionAccess().getEntityDependenceConditionsAssignment_3_1(), "rule__Condition__EntityDependenceConditionsAssignment_3_1");
					put(grammarAccess.getConditionAccess().getAttributeAchieveConditionsAssignment_4_1(), "rule__Condition__AttributeAchieveConditionsAssignment_4_1");
					put(grammarAccess.getConditionAccess().getAttributeInvariantConditionsAssignment_5_1(), "rule__Condition__AttributeInvariantConditionsAssignment_5_1");
					put(grammarAccess.getConditionAccess().getAttributeDependenceConditionsAssignment_6_1(), "rule__Condition__AttributeDependenceConditionsAssignment_6_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.blended.condition.ui.contentassist.antlr.internal.InternalConditionParser typedParser = (org.blended.condition.ui.contentassist.antlr.internal.InternalConditionParser) parser;
			typedParser.entryRuleConditionModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ConditionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ConditionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
