/*
 * generated by Xtext 2.12.0
 */
package pt.ist.socialsoftware.blendedworkflow.designer.ide


/**
 * Use this class to register ide components.
 */
class BlendedWorkflowIdeModule extends AbstractBlendedWorkflowIdeModule {
}
