/*
 * generated by Xtext
 */
package org.blended.data.ui;

import org.blended.data.generator.CustomOutputConfigurationProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.generator.IOutputConfigurationProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DataUiModule extends org.blended.data.ui.AbstractDataUiModule {
	public DataUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IOutputConfigurationProvider> bindIOutputConfigurationProvider() {
		return CustomOutputConfigurationProvider.class;
	}
}
