/**
 * generated by Xtext
 */
package org.blended.activity.ui.labeling;

import com.google.inject.Inject;
import org.blended.activity.activity.Activity;
import org.blended.activity.activity.ActivityModel;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class ActivityLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public ActivityLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String image(final ActivityModel am) {
    return "activities.gif";
  }
  
  public String text(final ActivityModel am) {
    return "Activities";
  }
  
  public String image(final Activity a) {
    return "activity.png";
  }
  
  public String text(final Activity a) {
    String _name = a.getName();
    String _plus = (_name + " (");
    String _description = a.getDescription();
    String _plus_1 = (_plus + _description);
    return (_plus_1 + ")");
  }
}
