/*
 * generated by Xtext
 */
package org.blended.goal.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.blended.goal.services.GoalGrammarAccess;

public class GoalParser extends AbstractContentAssistParser {
	
	@Inject
	private GoalGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.blended.goal.ui.contentassist.antlr.internal.InternalGoalParser createParser() {
		org.blended.goal.ui.contentassist.antlr.internal.InternalGoalParser result = new org.blended.goal.ui.contentassist.antlr.internal.InternalGoalParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getBlendedModelAccess().getAlternatives(), "rule__BlendedModel__Alternatives");
					put(grammarAccess.getAttributeAchieveConditionAccess().getAlternatives(), "rule__AttributeAchieveCondition__Alternatives");
					put(grammarAccess.getCardinalityAccess().getAlternatives(), "rule__Cardinality__Alternatives");
					put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
					put(grammarAccess.getAtomicAccess().getAlternatives(), "rule__Atomic__Alternatives");
					put(grammarAccess.getConditionAccess().getEntityAchieveConditionsAlternatives_1_1_0(), "rule__Condition__EntityAchieveConditionsAlternatives_1_1_0");
					put(grammarAccess.getGoalAccess().getSucessConditionAlternatives_4_0(), "rule__Goal__SucessConditionAlternatives_4_0");
					put(grammarAccess.getGoalAccess().getActivationConditionAlternatives_6_3_0(), "rule__Goal__ActivationConditionAlternatives_6_3_0");
					put(grammarAccess.getGoalAccess().getInvariantConditionsAlternatives_7_3_0(), "rule__Goal__InvariantConditionsAlternatives_7_3_0");
					put(grammarAccess.getGoalAccess().getInvariantConditionsAlternatives_7_4_1_0(), "rule__Goal__InvariantConditionsAlternatives_7_4_1_0");
					put(grammarAccess.getActivityAccess().getPreAlternatives_5_0_0(), "rule__Activity__PreAlternatives_5_0_0");
					put(grammarAccess.getActivityAccess().getPreAlternatives_5_1_1_0(), "rule__Activity__PreAlternatives_5_1_1_0");
					put(grammarAccess.getActivityAccess().getPostAlternatives_10_0_0(), "rule__Activity__PostAlternatives_10_0_0");
					put(grammarAccess.getActivityAccess().getPostAlternatives_10_1_1_0(), "rule__Activity__PostAlternatives_10_1_1_0");
					put(grammarAccess.getEntityAchieveConditionAccess().getGroup(), "rule__EntityAchieveCondition__Group__0");
					put(grammarAccess.getEntityAchieveConditionExistAccess().getGroup(), "rule__EntityAchieveConditionExist__Group__0");
					put(grammarAccess.getEntityInvariantConditionAccess().getGroup(), "rule__EntityInvariantCondition__Group__0");
					put(grammarAccess.getEntityDependenceConditionAccess().getGroup(), "rule__EntityDependenceCondition__Group__0");
					put(grammarAccess.getNotMandatoryAttributeAchieveConditionAccess().getGroup(), "rule__NotMandatoryAttributeAchieveCondition__Group__0");
					put(grammarAccess.getNotMandatoryAttributeAchieveConditionAccess().getGroup_3(), "rule__NotMandatoryAttributeAchieveCondition__Group_3__0");
					put(grammarAccess.getMandatoryAttributeAchieveConditionAccess().getGroup(), "rule__MandatoryAttributeAchieveCondition__Group__0");
					put(grammarAccess.getMandatoryAttributeAchieveConditionAccess().getGroup_5(), "rule__MandatoryAttributeAchieveCondition__Group_5__0");
					put(grammarAccess.getAttributeInvariantConditionAccess().getGroup(), "rule__AttributeInvariantCondition__Group__0");
					put(grammarAccess.getAttributeDependenceConditionAccess().getGroup(), "rule__AttributeDependenceCondition__Group__0");
					put(grammarAccess.getAttributeDependenceConditionAccess().getGroup_5(), "rule__AttributeDependenceCondition__Group_5__0");
					put(grammarAccess.getCardinalityAccess().getGroup_1(), "rule__Cardinality__Group_1__0");
					put(grammarAccess.getCardinalityAccess().getGroup_2(), "rule__Cardinality__Group_2__0");
					put(grammarAccess.getCardinalityAccess().getGroup_3(), "rule__Cardinality__Group_3__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup_3(), "rule__Attribute__Group_3__0");
					put(grammarAccess.getOrAccess().getGroup(), "rule__Or__Group__0");
					put(grammarAccess.getOrAccess().getGroup_1(), "rule__Or__Group_1__0");
					put(grammarAccess.getAndAccess().getGroup(), "rule__And__Group__0");
					put(grammarAccess.getAndAccess().getGroup_1(), "rule__And__Group_1__0");
					put(grammarAccess.getPrimaryAccess().getGroup_0(), "rule__Primary__Group_0__0");
					put(grammarAccess.getPrimaryAccess().getGroup_1(), "rule__Primary__Group_1__0");
					put(grammarAccess.getAtomicAccess().getGroup_0(), "rule__Atomic__Group_0__0");
					put(grammarAccess.getAtomicAccess().getGroup_1(), "rule__Atomic__Group_1__0");
					put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
					put(grammarAccess.getConditionAccess().getGroup_1(), "rule__Condition__Group_1__0");
					put(grammarAccess.getConditionAccess().getGroup_2(), "rule__Condition__Group_2__0");
					put(grammarAccess.getConditionAccess().getGroup_3(), "rule__Condition__Group_3__0");
					put(grammarAccess.getConditionAccess().getGroup_4(), "rule__Condition__Group_4__0");
					put(grammarAccess.getConditionAccess().getGroup_5(), "rule__Condition__Group_5__0");
					put(grammarAccess.getConditionAccess().getGroup_6(), "rule__Condition__Group_6__0");
					put(grammarAccess.getGoalAccess().getGroup(), "rule__Goal__Group__0");
					put(grammarAccess.getGoalAccess().getGroup_6(), "rule__Goal__Group_6__0");
					put(grammarAccess.getGoalAccess().getGroup_7(), "rule__Goal__Group_7__0");
					put(grammarAccess.getGoalAccess().getGroup_7_4(), "rule__Goal__Group_7_4__0");
					put(grammarAccess.getGoalAccess().getGroup_8(), "rule__Goal__Group_8__0");
					put(grammarAccess.getGoalAccess().getGroup_8_4(), "rule__Goal__Group_8_4__0");
					put(grammarAccess.getActivityAccess().getGroup(), "rule__Activity__Group__0");
					put(grammarAccess.getActivityAccess().getGroup_5(), "rule__Activity__Group_5__0");
					put(grammarAccess.getActivityAccess().getGroup_5_1(), "rule__Activity__Group_5_1__0");
					put(grammarAccess.getActivityAccess().getGroup_10(), "rule__Activity__Group_10__0");
					put(grammarAccess.getActivityAccess().getGroup_10_1(), "rule__Activity__Group_10_1__0");
					put(grammarAccess.getGoalModelAccess().getGoalsAssignment(), "rule__GoalModel__GoalsAssignment");
					put(grammarAccess.getEntityAchieveConditionAccess().getNameAssignment_2(), "rule__EntityAchieveCondition__NameAssignment_2");
					put(grammarAccess.getEntityAchieveConditionExistAccess().getNameAssignment_4(), "rule__EntityAchieveConditionExist__NameAssignment_4");
					put(grammarAccess.getEntityInvariantConditionAccess().getNameAssignment_2(), "rule__EntityInvariantCondition__NameAssignment_2");
					put(grammarAccess.getEntityInvariantConditionAccess().getCardinalityAssignment_4(), "rule__EntityInvariantCondition__CardinalityAssignment_4");
					put(grammarAccess.getEntityDependenceConditionAccess().getEntity1Assignment_4(), "rule__EntityDependenceCondition__Entity1Assignment_4");
					put(grammarAccess.getEntityDependenceConditionAccess().getEntity2Assignment_9(), "rule__EntityDependenceCondition__Entity2Assignment_9");
					put(grammarAccess.getNotMandatoryAttributeAchieveConditionAccess().getConditionsAssignment_2(), "rule__NotMandatoryAttributeAchieveCondition__ConditionsAssignment_2");
					put(grammarAccess.getNotMandatoryAttributeAchieveConditionAccess().getConditionsAssignment_3_1(), "rule__NotMandatoryAttributeAchieveCondition__ConditionsAssignment_3_1");
					put(grammarAccess.getMandatoryAttributeAchieveConditionAccess().getConditionsAssignment_4(), "rule__MandatoryAttributeAchieveCondition__ConditionsAssignment_4");
					put(grammarAccess.getMandatoryAttributeAchieveConditionAccess().getConditionsAssignment_5_1(), "rule__MandatoryAttributeAchieveCondition__ConditionsAssignment_5_1");
					put(grammarAccess.getAttributeInvariantConditionAccess().getExpressionAssignment_2(), "rule__AttributeInvariantCondition__ExpressionAssignment_2");
					put(grammarAccess.getAttributeDependenceConditionAccess().getAttributes1Assignment_4(), "rule__AttributeDependenceCondition__Attributes1Assignment_4");
					put(grammarAccess.getAttributeDependenceConditionAccess().getAttributes1Assignment_5_1(), "rule__AttributeDependenceCondition__Attributes1Assignment_5_1");
					put(grammarAccess.getAttributeDependenceConditionAccess().getAttribute2Assignment_10(), "rule__AttributeDependenceCondition__Attribute2Assignment_10");
					put(grammarAccess.getNothingAccess().getNameAssignment(), "rule__Nothing__NameAssignment");
					put(grammarAccess.getOrAccess().getRightAssignment_1_2(), "rule__Or__RightAssignment_1_2");
					put(grammarAccess.getAndAccess().getRightAssignment_1_2(), "rule__And__RightAssignment_1_2");
					put(grammarAccess.getPrimaryAccess().getExpressionAssignment_1_2(), "rule__Primary__ExpressionAssignment_1_2");
					put(grammarAccess.getAtomicAccess().getNameAssignment_0_3(), "rule__Atomic__NameAssignment_0_3");
					put(grammarAccess.getAtomicAccess().getNameAssignment_1_1(), "rule__Atomic__NameAssignment_1_1");
					put(grammarAccess.getConditionAccess().getEntityAchieveConditionsAssignment_1_1(), "rule__Condition__EntityAchieveConditionsAssignment_1_1");
					put(grammarAccess.getConditionAccess().getEntityInvariantConditionsAssignment_2_1(), "rule__Condition__EntityInvariantConditionsAssignment_2_1");
					put(grammarAccess.getConditionAccess().getEntityDependenceConditionsAssignment_3_1(), "rule__Condition__EntityDependenceConditionsAssignment_3_1");
					put(grammarAccess.getConditionAccess().getAttributeAchieveConditionsAssignment_4_1(), "rule__Condition__AttributeAchieveConditionsAssignment_4_1");
					put(grammarAccess.getConditionAccess().getAttributeInvariantConditionsAssignment_5_1(), "rule__Condition__AttributeInvariantConditionsAssignment_5_1");
					put(grammarAccess.getConditionAccess().getAttributeDependenceConditionsAssignment_6_1(), "rule__Condition__AttributeDependenceConditionsAssignment_6_1");
					put(grammarAccess.getGoalAccess().getNameAssignment_0(), "rule__Goal__NameAssignment_0");
					put(grammarAccess.getGoalAccess().getSucessConditionAssignment_4(), "rule__Goal__SucessConditionAssignment_4");
					put(grammarAccess.getGoalAccess().getActivationConditionAssignment_6_3(), "rule__Goal__ActivationConditionAssignment_6_3");
					put(grammarAccess.getGoalAccess().getInvariantConditionsAssignment_7_3(), "rule__Goal__InvariantConditionsAssignment_7_3");
					put(grammarAccess.getGoalAccess().getInvariantConditionsAssignment_7_4_1(), "rule__Goal__InvariantConditionsAssignment_7_4_1");
					put(grammarAccess.getGoalAccess().getChildrenGoalsAssignment_8_3(), "rule__Goal__ChildrenGoalsAssignment_8_3");
					put(grammarAccess.getGoalAccess().getChildrenGoalsAssignment_8_4_1(), "rule__Goal__ChildrenGoalsAssignment_8_4_1");
					put(grammarAccess.getActivityAccess().getNameAssignment_0(), "rule__Activity__NameAssignment_0");
					put(grammarAccess.getActivityAccess().getDescriptionAssignment_2(), "rule__Activity__DescriptionAssignment_2");
					put(grammarAccess.getActivityAccess().getPreAssignment_5_0(), "rule__Activity__PreAssignment_5_0");
					put(grammarAccess.getActivityAccess().getPreAssignment_5_1_1(), "rule__Activity__PreAssignment_5_1_1");
					put(grammarAccess.getActivityAccess().getPostAssignment_10_0(), "rule__Activity__PostAssignment_10_0");
					put(grammarAccess.getActivityAccess().getPostAssignment_10_1_1(), "rule__Activity__PostAssignment_10_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.blended.goal.ui.contentassist.antlr.internal.InternalGoalParser typedParser = (org.blended.goal.ui.contentassist.antlr.internal.InternalGoalParser) parser;
			typedParser.entryRuleGoalModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public GoalGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GoalGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
