/*
 * generated by Xtext
 */
package org.blended.activity.validation

import org.blended.activity.activity.ActivityModel
import org.blended.activity.activity.ActivityPackage
import org.eclipse.xtext.validation.Check
import org.eclipse.xtext.validation.CheckType

import static extension org.eclipse.xtext.EcoreUtil2.*
import org.blended.activity.repository.WriteActivityModelService

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class ActivityValidator extends AbstractActivityValidator {

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check(CheckType.NORMAL)
	def checkModel(ActivityModel model) {
				info('everything OK 0', ActivityPackage.Literals.ACTIVITY_MODEL__SPECIFICATION)
		var instance = WriteActivityModelService.getInstance
				info('everything OK 2', ActivityPackage.Literals.ACTIVITY_MODEL__SPECIFICATION)
		var specId = model.eResource.normalizedURI.lastSegment.split("\\.").get(0)
				info('everything OK 3', ActivityPackage.Literals.ACTIVITY_MODEL__SPECIFICATION)
		var notification = instance.write(specId, model)
				info('everything OK 4', ActivityPackage.Literals.ACTIVITY_MODEL__SPECIFICATION)
		if (notification.hasErrors)
			for (error : notification.error)
				error(error.type.toString + "-" + error.value, ActivityPackage.Literals.ACTIVITY_MODEL__SPECIFICATION)
		else
			info('everything OK 2', ActivityPackage.Literals.ACTIVITY_MODEL__SPECIFICATION)
	}

}
