/*
 * generated by Xtext
 */
package org.blended.goal;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GoalUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.blended.goal.ui.internal.GoalActivator.getInstance().getInjector("org.blended.goal.Goal");
	}
	
}
