/*
 * generated by Xtext
 */
package org.blended.goal;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GoalStandaloneSetup extends GoalStandaloneSetupGenerated{

	public static void doSetup() {
		new GoalStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

