/*
 * generated by Xtext
 */
package org.blended.activity.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.blended.activity.services.ActivityGrammarAccess;

public class ActivityParser extends AbstractContentAssistParser {
	
	@Inject
	private ActivityGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.blended.activity.ui.contentassist.antlr.internal.InternalActivityParser createParser() {
		org.blended.activity.ui.contentassist.antlr.internal.InternalActivityParser result = new org.blended.activity.ui.contentassist.antlr.internal.InternalActivityParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAttributeAchieveConditionAccess().getAlternatives(), "rule__AttributeAchieveCondition__Alternatives");
					put(grammarAccess.getCardinalityAccess().getAlternatives(), "rule__Cardinality__Alternatives");
					put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
					put(grammarAccess.getAtomicAccess().getAlternatives(), "rule__Atomic__Alternatives");
					put(grammarAccess.getActivityAccess().getPreAlternatives_5_0_0(), "rule__Activity__PreAlternatives_5_0_0");
					put(grammarAccess.getActivityAccess().getPreAlternatives_5_1_1_0(), "rule__Activity__PreAlternatives_5_1_1_0");
					put(grammarAccess.getActivityAccess().getPostAlternatives_10_0_0(), "rule__Activity__PostAlternatives_10_0_0");
					put(grammarAccess.getActivityAccess().getPostAlternatives_10_1_1_0(), "rule__Activity__PostAlternatives_10_1_1_0");
					put(grammarAccess.getEntityAchieveConditionAccess().getGroup(), "rule__EntityAchieveCondition__Group__0");
					put(grammarAccess.getEntityAchieveConditionExistAccess().getGroup(), "rule__EntityAchieveConditionExist__Group__0");
					put(grammarAccess.getEntityInvariantConditionAccess().getGroup(), "rule__EntityInvariantCondition__Group__0");
					put(grammarAccess.getEntityDependenceConditionAccess().getGroup(), "rule__EntityDependenceCondition__Group__0");
					put(grammarAccess.getNotMandatoryAttributeAchieveConditionAccess().getGroup(), "rule__NotMandatoryAttributeAchieveCondition__Group__0");
					put(grammarAccess.getNotMandatoryAttributeAchieveConditionAccess().getGroup_3(), "rule__NotMandatoryAttributeAchieveCondition__Group_3__0");
					put(grammarAccess.getMandatoryAttributeAchieveConditionAccess().getGroup(), "rule__MandatoryAttributeAchieveCondition__Group__0");
					put(grammarAccess.getMandatoryAttributeAchieveConditionAccess().getGroup_5(), "rule__MandatoryAttributeAchieveCondition__Group_5__0");
					put(grammarAccess.getAttributeInvariantConditionAccess().getGroup(), "rule__AttributeInvariantCondition__Group__0");
					put(grammarAccess.getAttributeDependenceConditionAccess().getGroup(), "rule__AttributeDependenceCondition__Group__0");
					put(grammarAccess.getAttributeDependenceConditionAccess().getGroup_5(), "rule__AttributeDependenceCondition__Group_5__0");
					put(grammarAccess.getCardinalityAccess().getGroup_1(), "rule__Cardinality__Group_1__0");
					put(grammarAccess.getCardinalityAccess().getGroup_2(), "rule__Cardinality__Group_2__0");
					put(grammarAccess.getCardinalityAccess().getGroup_3(), "rule__Cardinality__Group_3__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup_3(), "rule__Attribute__Group_3__0");
					put(grammarAccess.getOrAccess().getGroup(), "rule__Or__Group__0");
					put(grammarAccess.getOrAccess().getGroup_1(), "rule__Or__Group_1__0");
					put(grammarAccess.getAndAccess().getGroup(), "rule__And__Group__0");
					put(grammarAccess.getAndAccess().getGroup_1(), "rule__And__Group_1__0");
					put(grammarAccess.getPrimaryAccess().getGroup_0(), "rule__Primary__Group_0__0");
					put(grammarAccess.getPrimaryAccess().getGroup_1(), "rule__Primary__Group_1__0");
					put(grammarAccess.getAtomicAccess().getGroup_0(), "rule__Atomic__Group_0__0");
					put(grammarAccess.getAtomicAccess().getGroup_1(), "rule__Atomic__Group_1__0");
					put(grammarAccess.getActivityAccess().getGroup(), "rule__Activity__Group__0");
					put(grammarAccess.getActivityAccess().getGroup_5(), "rule__Activity__Group_5__0");
					put(grammarAccess.getActivityAccess().getGroup_5_1(), "rule__Activity__Group_5_1__0");
					put(grammarAccess.getActivityAccess().getGroup_10(), "rule__Activity__Group_10__0");
					put(grammarAccess.getActivityAccess().getGroup_10_1(), "rule__Activity__Group_10_1__0");
					put(grammarAccess.getActivityModelAccess().getActivitiesAssignment(), "rule__ActivityModel__ActivitiesAssignment");
					put(grammarAccess.getEntityAchieveConditionAccess().getNameAssignment_2(), "rule__EntityAchieveCondition__NameAssignment_2");
					put(grammarAccess.getEntityAchieveConditionExistAccess().getNameAssignment_4(), "rule__EntityAchieveConditionExist__NameAssignment_4");
					put(grammarAccess.getEntityInvariantConditionAccess().getNameAssignment_2(), "rule__EntityInvariantCondition__NameAssignment_2");
					put(grammarAccess.getEntityInvariantConditionAccess().getCardinalityAssignment_4(), "rule__EntityInvariantCondition__CardinalityAssignment_4");
					put(grammarAccess.getEntityDependenceConditionAccess().getEntity1Assignment_4(), "rule__EntityDependenceCondition__Entity1Assignment_4");
					put(grammarAccess.getEntityDependenceConditionAccess().getEntity2Assignment_9(), "rule__EntityDependenceCondition__Entity2Assignment_9");
					put(grammarAccess.getNotMandatoryAttributeAchieveConditionAccess().getConditionsAssignment_2(), "rule__NotMandatoryAttributeAchieveCondition__ConditionsAssignment_2");
					put(grammarAccess.getNotMandatoryAttributeAchieveConditionAccess().getConditionsAssignment_3_1(), "rule__NotMandatoryAttributeAchieveCondition__ConditionsAssignment_3_1");
					put(grammarAccess.getMandatoryAttributeAchieveConditionAccess().getConditionsAssignment_4(), "rule__MandatoryAttributeAchieveCondition__ConditionsAssignment_4");
					put(grammarAccess.getMandatoryAttributeAchieveConditionAccess().getConditionsAssignment_5_1(), "rule__MandatoryAttributeAchieveCondition__ConditionsAssignment_5_1");
					put(grammarAccess.getAttributeInvariantConditionAccess().getExpressionAssignment_2(), "rule__AttributeInvariantCondition__ExpressionAssignment_2");
					put(grammarAccess.getAttributeDependenceConditionAccess().getAttributes1Assignment_4(), "rule__AttributeDependenceCondition__Attributes1Assignment_4");
					put(grammarAccess.getAttributeDependenceConditionAccess().getAttributes1Assignment_5_1(), "rule__AttributeDependenceCondition__Attributes1Assignment_5_1");
					put(grammarAccess.getAttributeDependenceConditionAccess().getAttribute2Assignment_10(), "rule__AttributeDependenceCondition__Attribute2Assignment_10");
					put(grammarAccess.getNothingAccess().getNameAssignment(), "rule__Nothing__NameAssignment");
					put(grammarAccess.getOrAccess().getRightAssignment_1_2(), "rule__Or__RightAssignment_1_2");
					put(grammarAccess.getAndAccess().getRightAssignment_1_2(), "rule__And__RightAssignment_1_2");
					put(grammarAccess.getPrimaryAccess().getExpressionAssignment_1_2(), "rule__Primary__ExpressionAssignment_1_2");
					put(grammarAccess.getAtomicAccess().getNameAssignment_0_3(), "rule__Atomic__NameAssignment_0_3");
					put(grammarAccess.getAtomicAccess().getNameAssignment_1_1(), "rule__Atomic__NameAssignment_1_1");
					put(grammarAccess.getActivityAccess().getNameAssignment_0(), "rule__Activity__NameAssignment_0");
					put(grammarAccess.getActivityAccess().getDescriptionAssignment_2(), "rule__Activity__DescriptionAssignment_2");
					put(grammarAccess.getActivityAccess().getPreAssignment_5_0(), "rule__Activity__PreAssignment_5_0");
					put(grammarAccess.getActivityAccess().getPreAssignment_5_1_1(), "rule__Activity__PreAssignment_5_1_1");
					put(grammarAccess.getActivityAccess().getPostAssignment_10_0(), "rule__Activity__PostAssignment_10_0");
					put(grammarAccess.getActivityAccess().getPostAssignment_10_1_1(), "rule__Activity__PostAssignment_10_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.blended.activity.ui.contentassist.antlr.internal.InternalActivityParser typedParser = (org.blended.activity.ui.contentassist.antlr.internal.InternalActivityParser) parser;
			typedParser.entryRuleActivityModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ActivityGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ActivityGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
