/*
 * generated by Xtext 2.12.0
 */
package pt.ist.socialsoftware.blendedworkflow.designer.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class BlendedWorkflowIdeaModule extends AbstractBlendedWorkflowIdeaModule {
}
