/*
 * generated by Xtext 2.12.0
 */
package pt.ist.socialsoftware.blendedworkflow.designer.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class BlendedWorkflowIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new BlendedWorkflowStandaloneSetupIdea().createInjector
	}

}
