/**
 * generated by Xtext
 */
package org.blended.activity.validation;

import org.blended.activity.validation.AbstractActivityValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ActivityValidator extends AbstractActivityValidator {
}
