/*
 * generated by Xtext
 */
package org.blended.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BlendedUiModule extends org.blended.ui.AbstractBlendedUiModule {
	public BlendedUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
