export const SELECT_SPECIFICATION = "SELECT_SPECIFICATION";
export const SELECT_INSTANCE = "SELECT_INSTANCE";
export const GET_ENTITY_INSTANCES = "GET_ENTITY_INSTANCES";
export const SET_ENTITY_INSTANCES_TO_DEFINE = "SET_ENTITY_INSTANCES_TO_DEFINE";
export const CLEAR_ENTITY_INSTANCES_TO_DEFINE = "CLEAR_ENTITY_INSTANCES_TO_DEFINE";
export const SET_UNIT_OF_WORK = "SET_UNIT_OF_WORK";