/*
 * generated by Xtext
 */
package org.blended.data;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DataRuntimeModule extends org.blended.data.AbstractDataRuntimeModule {

	
}


