package pt.ist.socialsoftware.blendedworkflow.resources.service;

import pt.ist.socialsoftware.blendedworkflow.core.service.BWErrorType;

public enum RMErrorType {
    INVALID_RESOURCE_NAME, MISSING_POSITION_UNIT, INVALID_UNIT_NAME, INVALID_POSITION_NAME, INVALID_ROLE_NAME, INVALID_PERSON_NAME, INVALID_CAPABILITY_NAME, INVALID_RAL_EXPRESSION_TYPE, INVALID_RAL_EXPRESSION_DTO_TYPE, INVALID_ENTITY_NAME, INVALID_DATA_FIELD, ENTITY_IN_EXPRESSION_IS_NOT_PERSON,
}
